name: CI/CD Pipeline

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup SSH Key and known hosts for Server
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.GILVER_ADMIN_KEY }}

    - name: SSH and Pull Repo on Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@18.198.22.47 <<EOF
          cd /var/www/html/road_mgmt
          git pull origin master
          sudo service apache2 restart
        EOF
