name: Deploy

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GILVER_ADMIN_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to AWS instance
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_IP }} "
          sudo apt update
          sudo apt install apache2 -y
          sudo apt install php libapache2-mod-php php-mysql -y
          curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
          git clone git@github.com:Elsilaves/road_mgmt.git
          cd road_mgmt
          git pull origin master
          composer install
          cp .env.example .env
          php artisan key:generate
          php artisan migrate
          sudo chown -R www-data:www-data .
          sudo chmod -R 755 .
          # Copy Laravel app into Apache directory
          sudo cp -r * /var/www/html
        "
