name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-env:
    runs-on: self-hosted

    

  deploy-to-ec2:
    needs: [setup-env]
    runs-on: self-hosted
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
      - name: Install Apache
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2
