name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}
        ssh-key: ${{ secrets.SSH_KEY }}
        persist-credentials: false
      env:
        HTTP_PROXY: ''
        HTTPS_PROXY: ''

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1.2'

    - name: Install Composer Dependencies
      run: composer install

    - name: Copy Environment File
      run: cp .env.example .env

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit
